name: Build TDLib

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    name: Build TDLib (${{ matrix.platform }}-${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            arch: x86_64
            os: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-${{ matrix.platform }}-${{ matrix.arch }}

      - name: Install dependencies (Linux/Android)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y make zlib1g-dev libssl-dev gperf cmake php-cli ninja-build

      - name: Configure build (Linux)
        if: runner.os == 'Linux'
        run: cmake
          -GNinja
          -B build
          -S third_party/td
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_TESTING=0
          -DTD_GENERATE_SOURCE_FILES=0

      - name: Build TDLib
        run: cmake --build build --target tdjson -j$(nproc)

      - name: Install / Package
        run: |
          mkdir -p output/${{ matrix.platform }}/${{ matrix.arch }}
          cp build/libtdjson.so output/${{ matrix.platform }}/${{ matrix.arch }} || true
          ls -l

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-${{ matrix.platform }}-${{ matrix.arch }}
          path: output/${{ matrix.platform }}/${{ matrix.arch }}
