name: Build TDLib

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    name: Build TDLib (${{ matrix.platform }}-${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            arch: x86_64
            os: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-${{ matrix.platform }}-${{ matrix.arch }}

      - name: Install dependencies (Linux/Android)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y make zlib1g-dev libssl-dev gperf cmake php-cli ninja-build clang libc++-dev libc++abi-dev

      - name: Configure build (Linux)
        if: runner.os == 'Linux'
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
          CXXFLAGS: -stdlib=libc++
        run: cmake -GNinja -B build -S third_party/td -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build TDLib
        run: |
          cd build
          cmake --build . --target prepare_cross_compiling -j$(nproc)
          cmake --build . --target tdjson -j$(nproc)

      - name: Install / Package
        run: |
          mkdir -p output/${{ matrix.platform }}/${{ matrix.arch }}
          cp build/libtdjson.so output/${{ matrix.platform }}/${{ matrix.arch }} || true
          ls -l output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-${{ matrix.platform }}-${{ matrix.arch }}
          path: output/${{ matrix.platform }}/${{ matrix.arch }}
