name: Build TDLib

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: setup
        run: sudo apt-get install -y make zlib1g-dev libssl-dev gperf php-cli cmake clang libc++-dev libc++abi-dev

      - name: build
        run: |
          cd third_party/td
          rm -rf build && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
          cmake --build . --target prepare_cross_compiling
          cmake --build . --target install

      - name: pack
        run: cd third_party/td/tdlib/lib && zip libtdjson.zip libtdjson.so && mv libtdjson.zip ../../../..

      - name: GH Release
        uses: softprops/action-gh-release@v2.4.1
        if: github.ref_type == 'tag'
        with:
          files: libtdjson.zip
